baseURL = "https://www.underkube.com/"
title = "Underkube"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Underkube"
    subtitle = "Tips, tricks and all things k8s/OpenShift/containers/etc"
    keywords = ""
    copyright = "CC-BY-SA 4.0"
    menuMore = "Tags"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Underkube"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/page/about"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"

      [[languages.en.menu.main]]
	      identifier = "rss"
        name = "RSS"
        url = "/post/index.xml"

      [[languages.en.menu.main]]
        identifier = "tag1"
        name = "OpenShift"
        url = "/tags/openshift"

     [[languages.en.menu.main]]
        identifier = "tag2"
        name = "Kubernetes"
        url = "/tags/kubernetes"
