baseURL = "https://www.underkube.com/"
title = "Underkube"
theme = "cactus-plus"
hasCJKLanguage = false
languageCode = "en-us"
#googleAnalytics = "your_google_analytics_id"

[params]
  description = "Tips, tricks and all things k8s/OpenShift/containers/etc"
  author = "Eduardo Mínguez"
  twitter = "minWi"
  enableRSS = true
	enableToc = true
  enableDisqus = false
  enableSummary = false
  # Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = false
	enableBaiduAnalytics = false

  enableTwitterCard = true
  # The url for twitter card image, default is avatar.png in static/images directory
  twitterCardImage = ""

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  archive = "All Posts"
  subscribe = ""

  olderPosts = ""
  newerPosts = ""
  copyright = ""

  # show latest posts in single page
  showLatestPosts = false
  readMore = ""

  # Share
  enableShare = true
  tweet = ""
  share = ""

  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


  # Add additional social link entries underneath
  [social]
  twitter-square = "https://www.twitter.com/minwi"
  github-square = "https://www.github.com/e-minguez"
