baseURL = "https://www.underkube.com/"
languageCode = "en-us"
title = "Underkube"
theme = "basics"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  author = "Eduardo Minguez"
  subTitle = "Tips, tricks and all things k8s/OpenShift"
  description = "@minWi thoughts about k8s/OpenShift"
  gitlab = "minWi"
  github = "e-minguez"
  twitter = "minwi"
